name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application-local.properties 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application-local.properties

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 테스트는 제외하고 빌드하기
        run: ./gradlew build -x test

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/Tlog-0.0.1-DEMO.jar ./Tlog-0.0.1-DEMO.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}           # EC2 IP 주소
          username: ${{ secrets.EC2_USERNAME }}   # 접속 사용자명
          key: ${{ secrets.EC2_PRIVATE_KEY }}     # .pem 키 파일 내용
          source: Tlog-0.0.1-DEMO.jar
          target: /home/ec2-user/team12-Tlog-BE/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}           # EC2 IP 주소
          username: ${{ secrets.EC2_USERNAME }}   # 접속 사용자명
          key: ${{ secrets.EC2_PRIVATE_KEY }}     # .pem 키 파일 내용
          script_stop: true
          script: |
            rm -rf /home/ec2-user/team12-Tlog-BE/current
            mkdir /home/ec2-user/team12-Tlog-BE/current
            mv /home/ec2-user/team12-Tlog-BE/tobe/Tlog-0.0.1-DEMO.jar /home/ec2-user/team12-Tlog-BE/current/Tlog-0.0.1-DEMO.jar
            cd /home/ec2-user/team12-Tlog-BE/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar Tlog-0.0.1-DEMO.jar > ./output.log 2>&1 &
            rm -rf /home/ec2-user/team12-Tlog-BE/tobe